name: integration-tests
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        # 10x em parelo
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          record: true
          parallel: true
          group: 'Integration tests'
          start: npm run serve
        env:
          CYPRESS_RECORD_KEY: a64a7266-58c4-44bf-9e8b-c07852a59166
