# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:name: Bussola Social E2E
on:
  push:
    branches:
      - 'master'

jobs:
  
  cypress-e2e-chrome81:
    name: Run on Chrome 81
    runs-on: ubuntu-18.04
    container: cypress/browsers:node12.16.2-chrome81-ff75
    steps:
      - uses: actions/checkout@v2
      
      - name: Install a project with a clean slate
        run: |
          npm ci
          $(npm bin)/cypress cache path
          $(npm bin)/cypress cache list
          $(npm bin)/cypress verify
      
      - name: Rodar Testes Cypress 
        run: npm run test:chrome
        continue-on-error: true
      
      - name: Copiar pasta com videos de testes
        run: |
          cp -r cypress/videos reports/videos         

      - name: Copiar pasta com prints de testes
        run: |
          cp -r cypress/screenshots reports/screenshots
          
      - name: Fazer merger de todos testes gerados e um unico arquivo
        run: npm run report:merge
      
      - name: Gerar um relatorio HTML 
        run: npm run report:generate
      
      - name: Fazer deploy em um pagina do GithubPages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
